from typing import Protocol, runtime_checkable

from . import Stateful

@runtime_checkable
class Scalable(Protocol):
    def scale(factor: float) -> int:
        """
        Scales all values of a parameter and returns the number of dimensions.
        """

class Real(Stateful, Scalable):
    """
    Real multidimensional parameter

    It acts as a list of `float`s, except it implements
    [`Stateful`](#Stateful).  Note that this uses regular 64-bit floating point
    numbers underneath, not some custom arbitrary precision real type.
    """
    def __init__(self, *values: float): ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __float__(self) -> float: ...
    # richcmp
    def __lt__(self, other: float | Real) -> bool: ...
    def __le__(self, other: float | Real) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __gt__(self, other: float | Real) -> bool: ...
    def __ge__(self, other: float | Real) -> bool: ...

class Integer(Stateful):
    """
    Integer multidimensional parameter

    It acts as a list of `int`s, except it implements [`Stateful`](#Stateful).
    """
    def __init__(self, *values: int): ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __int__(self) -> int: ...
    # richcmp
    def __lt__(self, other: int | Integer) -> bool: ...
    def __le__(self, other: int | Integer) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __gt__(self, other: int | Integer) -> bool: ...
    def __ge__(self, other: int | Integer) -> bool: ...

class Boolean(Stateful):
    """
    Boolean multidimensional parameter

    It acts as a list of `bool`s, except it implements [`Stateful`](#Stateful).
    """

    def __init__(self, *values: bool): ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> bool: ...
    def __setitem__(self, index: int, value: bool) -> None: ...
    # richcmp
    def __lt__(self, other: bool | Boolean) -> bool: ...
    def __le__(self, other: bool | Boolean) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __gt__(self, other: bool | Boolean) -> bool: ...
    def __ge__(self, other: bool | Boolean) -> bool: ...

Parameter = Real | Integer | Boolean
