from __future__ import annotations

from collections.abc import Hashable, Iterator, Sequence
from dataclasses import dataclass
from datetime import timedelta
from typing import Optional, SupportsFloat

from ..b3 import Callback, Internal, Leaf, Node, Operator, Prior, Stateful, Tree
from ..b3.clocks import Clock
from ..b3.likelihoods import Likelihood
from ..b3.parameters import Scalable, Weights
from ..b3.substitutions import Substiution4
from ..data.msa import MSA
from ..data.newick import Tree as NewickTree
from ..rng import RNG
from ..stats.distributions import Sample

class Tree(Stateful):
    @classmethod
    def from_newick(_cls, newick: NewickTree) -> Tree: ...
    def set_random_topology(self, rng: RNG): ...
    def set_random_edges(self, rng: RNG): ...
    def set_random_heights(self, diff, rng: RNG): ...
    @property
    def names(self) -> list[str]: ...
    def scale(self, scale: float): ...
    def update_edge(self, edge: int, new_child: Node) -> None: ...
    def set_height(self, node: Node, weigth: float) -> None: ...
    def set_root(self, node: Node) -> None: ...
    def swap_parents(self, a: Node, b: Node) -> None: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_internals(self) -> int: ...
    @property
    def num_leaves(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    def is_internal(self, node: Node) -> bool: ...
    def is_leaf(self, node: Node) -> bool: ...
    @property
    def root(self) -> Internal: ...
    def height_of(self, node: Node) -> float: ...
    def children_of(self, node: Internal) -> tuple[Node, Node]: ...
    def other_child(self, parent: Internal, child: Node) -> Node: ...
    def random_intersecting_edge(self, height: float, rng: RNG) -> Optional[int]: ...
    def edge_index(self, child: Node) -> int: ...
    def edge_length(self, edge: int) -> float: ...
    def edge_nodes(self, edge: int) -> tuple[Node, Internal]: ...
    def parent_of(self, node: Node) -> Optional[Internal]: ...
    def is_grandparent(self, node: Internal) -> bool: ...
    def num_grandparents(self) -> int: ...
    def nodes(self) -> Iterator[Node]: ...
    def internals(self) -> Iterator[Internal]: ...
    def leaves(self) -> Iterator[Leaf]: ...
    def random_node(self, rng: RNG) -> Node: ...
    def random_nonroot_node(self, rng: RNG) -> tuple[Internal, Internal]: ...
    def random_internal(self, rng: RNG) -> Internal: ...
    def random_nonroot_internal(self, rng: RNG) -> tuple[Internal, Internal]: ...
    def random_leaf(self, rng: RNG) -> Leaf: ...
    def leaf_by_name(self, name: str) -> Optional[Leaf]: ...
    def total_length(self) -> float: ...
    def has_dated_tips(self) -> bool: ...
    def validate(self) -> None: ...
    def newick(self, internal_ids=False) -> str: ...

class Leaf(Hashable): ...
class Internal(Hashable): ...

class Proposal:
    @classmethod
    def Reject(cls) -> Proposal: ...
    @classmethod
    def Hastings(cls, ratio: float) -> Proposal: ...
    @classmethod
    def Accept(cls) -> Proposal: ...

class CPU4Likelihood(Likelihood):
    def __init__(
        self,
        msa: MSA,
        substitution: Substiution4,
        clock: Clock,
        tree: Tree,
        scale_ln: int = 30,
    ): ...

class Parallel4Likelihood(Likelihood):
    def __init__(
        self,
        msa: MSA,
        substitution: Substiution4,
        clock: Clock,
        tree: Tree,
        num_threads: int,
        scale_ln: int = 30,
    ): ...

class CUDALikelihood(Likelihood):
    def __init__(
        self,
        msa: MSA,
        substitution: Substiution4,
        clock: Clock,
        tree: Tree,
        *,
        cuda_device: int = 0,
    ): ...

class MCMC:
    def __init__(
        self,
        state: Sequence[Stateful],
        priors: Sequence[Prior],
        operators: Sequence[Operator],
        likelihood: Likelihood,
        callbacks: Sequence[Callback],
        rng: RNG,
    ): ...
    @property
    def current_step(self) -> int: ...
    @property
    def state(self) -> list[Stateful]: ...
    @property
    def priors(self) -> list[Prior]: ...
    @property
    def operators(self) -> list[Operator]: ...
    @property
    def likelihood(self) -> Likelihood: ...
    @property
    def callbacks(self) -> list[Callback]: ...
    @property
    def rng(self) -> RNG: ...
    @property
    def posterior(self) -> float: ...
    @property
    def prior(self) -> float: ...
    @property
    def operator_statistics(
        self,
    ) -> list[tuple[Operator, list[int], timedelta, timedelta]]: ...
    def run(self, n: int) -> None: ...
    def measure_operator(self, operator_index: int, length: int) -> list[int]: ...

@dataclass
class EpochScale(Operator):
    tree: Tree
    factor: float
    distribution: Sample[float]
    rng: RNG
    weight: float = 1

@dataclass(slots=True)
class SubtreeLeap(Operator):
    tree: Tree
    distribution: Sample[float]
    rng: RNG
    weight: float = 1

@dataclass
class ConstantPopulation(Prior):
    tree: Tree
    population: SupportsFloat

@dataclass
class ExponentialGrowth(Prior):
    tree: Tree
    population: SupportsFloat
    growth_rate: SupportsFloat

@dataclass
class Monophyly(Prior):
    tree: Tree
    leaves: Sequence[Leaf]

@dataclass
class Yule(Prior):
    tree: Tree
    birth_rate: SupportsFloat

class JC: ...

@dataclass
class K80:
    kappa: SupportsFloat

@dataclass
class HKY:
    frequencies: Weights | tuple[float, float, float, float]
    kappa: SupportsFloat
