from __future__ import annotations

from collections.abc import Hashable, Iterator, Sequence
from dataclasses import dataclass
from datetime import timedelta
from typing import Optional, Sized, SupportsFloat

from ..b3 import Callback, Operator, Prior, TunableOperator
from ..b3.likelihoods import Likelihood
from ..b3.parameters import Node, Parameter, Scalable
from ..b3.substitutions import Substitution4
from ..data.msa import MSA
from ..data.newick import Tree as NewickTree
from ..rng import RNG
from ..stats.distributions import ContinuousCDF, Sample

class Tree(Scalable):
    def __init__(self, names: list[str], rng: RNG): ...
    def set_random_topology(self, rng: RNG): ...
    def set_random_edges(self, rng: RNG): ...
    def set_random_heights(self, diff, rng: RNG): ...
    def load_newick(self, newick: NewickTree): ...
    @classmethod
    def simulate_coalescent(
        cls,
        names: Sequence[str],
        heights: Sequence[float],
        population_size: float,
        rng: RNG,
    ): ...
    @property
    def names(self) -> list[str]: ...
    def replace_child(
        self, parent: Internal, old_child: Node, new_child: Node
    ) -> None: ...
    def spr(self, node: Node, other: Node) -> None: ...
    def set_height(self, node: Node, weigth: float) -> None: ...
    def set_root(self, node: Node) -> None: ...
    def swap_parents(self, a: Node, b: Node) -> None: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_internals(self) -> int: ...
    @property
    def num_leaves(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    def is_internal(self, node: Node) -> bool: ...
    def is_leaf(self, node: Node) -> bool: ...
    @property
    def root(self) -> Internal: ...
    def height_of(self, node: Node) -> float: ...
    def children_of(self, node: Internal) -> tuple[Node, Node]: ...
    def other_child(self, parent: Internal, child: Node) -> Node: ...
    def edge_index(self, child: Node) -> int: ...
    def edge_length(self, edge: int) -> float: ...
    def edge_nodes(self, edge: int) -> tuple[Node, Internal]: ...
    def parent_of(self, node: Node) -> Optional[Internal]: ...
    def is_grandparent(self, node: Internal) -> bool: ...
    def num_grandparents(self) -> int: ...
    def nodes(self) -> Iterator[Node]: ...
    def internals(self) -> Iterator[Internal]: ...
    def leaves(self) -> Iterator[Leaf]: ...
    def random_node(self, rng: RNG) -> Node: ...
    def random_nonroot_node(self, rng: RNG) -> tuple[Internal, Internal]: ...
    def random_internal(self, rng: RNG) -> Internal: ...
    def random_nonroot_internal(self, rng: RNG) -> tuple[Internal, Internal]: ...
    def random_leaf(self, rng: RNG) -> Leaf: ...
    def leaf_by_name(self, name: str) -> Optional[Leaf]: ...
    def total_length(self) -> float: ...
    def has_dated_tips(self) -> bool: ...
    def validate(self) -> None: ...
    def to_newick(self, internal_ids=False) -> str: ...
    def ola(self) -> list[int]: ...
    def internal_heights(self) -> list[float]: ...
    # Parameter
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    def load(self, bytes: bytes) -> None: ...
    def dump(self) -> bytes: ...
    def is_changed(self) -> bool: ...

class Leaf(Hashable): ...
class Internal(Hashable): ...

class Proposal:
    @classmethod
    def Abort(cls) -> Proposal: ...
    @classmethod
    def Hastings(cls, ratio: float) -> Proposal: ...

class Calculator:
    @classmethod
    def CPU(cls, num_threads: int = 0) -> Calculator: ...
    @classmethod
    def CUDA(cls, device: int = 0) -> Calculator: ...
    def with_scale(self, scale: int) -> Calculator: ...

class DNALikelihood:
    def __init__(
        self,
        msa: MSA,
        substitution: Substitution4,
        clock: Clock,
        tree: Tree,
        calculator: Calculator,
    ): ...
    def likelihood(self) -> float: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class GammaLikelihood:
    def __init__(
        self,
        msa: MSA,
        substitution: Substitution4,
        num_categories: int,
        alpha: Real,
        clock: Clock,
        tree: Tree,
        calculator: Calculator,
    ): ...
    def likelihood(self) -> float: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class HeteroLikelihood:
    def __init__(
        self,
        msa: MSA,
        tree: Tree,
        categories: ClassVector,
        substitutions: list[Substitution4],
        clocks: list[Clock],
        calculator: Calculator,
    ): ...
    def likelihood(self) -> float: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    @property
    def sites_to_patterns(self) -> list[int]: ...

class CompoundLikelihood:
    def __init__(self, *likelihoods: Likelihood): ...
    def likelihood(self) -> float: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class MCMC:
    def __init__(
        self,
        priors: Sequence[Prior],
        operators: Sequence[Operator],
        likelihood: Likelihood,
        callbacks: Sequence[Callback],
        rng: RNG,
        optimization_cutoff: int = 1_000_000,
    ): ...
    @property
    def current_step(self) -> int: ...
    @property
    def parameters(self) -> list[Parameter]: ...
    @property
    def priors(self) -> list[Prior]: ...
    @property
    def operators(self) -> list[Operator]: ...
    @property
    def likelihood(self) -> Likelihood: ...
    @property
    def callbacks(self) -> list[Callback]: ...
    @property
    def rng(self) -> RNG: ...
    @property
    def posterior(self) -> float: ...
    @property
    def likelihood_value(self) -> float: ...
    @property
    def prior(self) -> float: ...
    @property
    def operator_statistics(
        self,
    ) -> list[tuple[Operator, list[int], timedelta, timedelta]]: ...
    def run(self, n: int) -> None: ...
    def dump_state(self) -> bytes: ...
    def load_state(self, state: bytes) -> None: ...

@dataclass(slots=True)
class SubtreeLeap(Operator, TunableOperator):
    tree: Tree
    distribution: Sample[float]
    rng: RNG
    weight: float = 1

@dataclass(slots=True)
class FixedHeightSPR(Operator):
    tree: Tree
    rng: RNG
    weight: float = 1

class ClassvecFlip(Operator):
    def __init__(self, classvec: ClassVector, rng: RNG, weight: float): ...

@dataclass
class SymmetricDirichlet(Prior):
    vec: RealVector
    sum: float

@dataclass
class ConstantPopulation(Prior):
    tree: Tree
    population: Real

@dataclass
class ExponentialGrowth(Prior):
    tree: Tree
    population: Real
    growth_rate: Real

@dataclass
class BayesianSkyline(Prior):
    tree: Tree
    population_sizes: RealVector
    group_sizes: IntVector

@dataclass
class Monophyly(Prior):
    tree: Tree
    leaves: Sequence[Leaf]

@dataclass
class Yule(Prior):
    tree: Tree
    birth_rate: Real

class JC: ...

@dataclass
class K80:
    kappa: Real

@dataclass
class HKY:
    frequencies: RealVector
    kappa: Real

@dataclass
class GTR:
    frequencies: RealVector
    rates: RealVector

class ClassVector(Sized):
    def __init__(self, num_classes: int, len: int): ...
    def into_list(self) -> list[int]: ...
    def is_changed(self) -> bool: ...

class Real(SupportsFloat, Scalable):
    def __init__(self, value: SupportsFloat): ...
    def set(self, value: SupportsFloat) -> None: ...
    def is_changed(self) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class RealVector(Sized):
    @classmethod
    def repeat(cls, value: float, length: int) -> RealVector: ...
    def is_changed(self) -> bool: ...
    def __init__(self, *values: SupportsFloat): ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float): ...
    def is_bound(self, lower: float, upper: float) -> bool: ...

class IntVector(Sized):
    @classmethod
    def repeat(cls, value: int, length: int) -> IntVector: ...
    def is_changed(self) -> bool: ...
    def __init__(self, *values: int): ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int): ...
    def is_bound(self, lower: Optional[int], upper: Optional[int]) -> bool: ...

class Clock:
    @classmethod
    def Strict(_cls, rate: Real) -> Clock: ...
    @classmethod
    def Relaxed(
        _cls, rate_categories: ClassVector, distribution: ContinuousCDF
    ) -> Clock: ...

class TraceWriter(Callback):
    def __init__(
        self,
        items: dict[str, Parameter | Prior],
        path: str,
        *,
        overwrite: bool = False,
        zstd: bool = False,
        every: int,
    ): ...

class OperatorStats(Callback):
    def __init__(self, path: str, *, every: int): ...
