from __future__ import annotations

from array import array
from collections.abc import Iterator
from os import PathLike

from ..rng import RNG

class AminoAcid:
    Alanine: AminoAcid
    Cysteine: AminoAcid
    AsparticAcid: AminoAcid
    GlutamicAcid: AminoAcid
    Phenylalanine: AminoAcid
    Glycine: AminoAcid
    Histidine: AminoAcid
    Isoleucine: AminoAcid
    Lysine: AminoAcid
    Leucine: AminoAcid
    Methionine: AminoAcid
    Asparagine: AminoAcid
    Proline: AminoAcid
    Glutamine: AminoAcid
    Arginine: AminoAcid
    Serine: AminoAcid
    Threonine: AminoAcid
    Valine: AminoAcid
    Tryptophan: AminoAcid
    Tyrosine: AminoAcid

    def __init__(self, char: str): ...

class DNANucleotide:
    Adenine: DNANucleotide
    Cytosine: DNANucleotide
    Guanine: DNANucleotide
    Thymine: DNANucleotide

    Weak: DNANucleotide
    Strong: DNANucleotide
    Amino: DNANucleotide
    Ketone: DNANucleotide
    Purine: DNANucleotide
    Pyrimidine: DNANucleotide

    NotAdenine: DNANucleotide
    NotCytosine: DNANucleotide
    NotGuanine: DNANucleotide
    NotThymine: DNANucleotide

    Any: DNANucleotide
    Gap: DNANucleotide

    def __init__(self, char: str): ...
    def __contains__(self, other: DNANucleotide) -> bool: ...
    def complement(self) -> DNANucleotide: ...

class DNASeq:
    def __init__(self, sequence: str | None): ...
    def __getitem__(self, index: int) -> DNANucleotide: ...
    def __len__(self) -> int: ...
    def complement(self) -> DNASeq: ...
    def reverse_complement(self) -> DNASeq: ...

class DNARecord:
    def __init__(self, name: str, sequence: DNASeq): ...
    @property
    def sequence(self) -> DNASeq: ...
    @property
    def description(self) -> str: ...
    @property
    def id(self) -> str: ...
    def __len__(self) -> int: ...

class Phred:
    def __init__(self, ch: str): ...
    def accuracy(self) -> float: ...
    def probability_incorrect(self) -> float: ...

class MSA:
    def __init__(self, names: TaxonSet, sequences: list[DNASeq]): ...
    @classmethod
    def from_fasta_file(cls, path: PathLike | str) -> MSA:
        """
        Create an alignment from FASTA records

        All records must have the same length.
        """

    @classmethod
    def random(
        _cls, num_sequences: int, num_sites: int, names: TaxonSet, rng: RNG
    ) -> MSA:
        """A random alignment of given dimensions"""

    @property
    def num_sites(self) -> int:
        """
        Number of sites in the alignment

        Some alignments might be partial, that is, they might reference fewer
        sites than their backing buffer has.  This can happen after slicing or
        some methods.
        """

    @property
    def num_sequences(self) -> int:
        """Number of sequences in the alignment"""

    def sequence_name(self, index: int) -> str:
        """The name (or id) of the `index`'th sequence"""

    def sequence_names(self) -> TaxonSet:
        """A list of all sequence names in the alignment"""

    def sequence(self, index: int) -> DNASeq:
        """The `index`'th sequence in the alignment"""

    def base_frequencies(self) -> tuple[float, float, float, float]:
        """
        Base frequencies of Adenine, Cytosine, Guanine, and Thymine, in that
        order
        """

class Node:
    @property
    def index(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: NodeId) -> bool: ...
    def __le__(self, other: NodeId) -> bool: ...
    def __gt__(self, other: NodeId) -> bool: ...
    def __ge__(self, other: NodeId) -> bool: ...

class Leaf:
    @property
    def index(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: NodeId) -> bool: ...
    def __le__(self, other: NodeId) -> bool: ...
    def __gt__(self, other: NodeId) -> bool: ...
    def __ge__(self, other: NodeId) -> bool: ...

class Internal:
    @property
    def index(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: NodeId) -> bool: ...
    def __le__(self, other: NodeId) -> bool: ...
    def __gt__(self, other: NodeId) -> bool: ...
    def __ge__(self, other: NodeId) -> bool: ...

type NodeId = Node | Leaf | Internal

class TreeBuilder:
    def __init__(self): ...
    @classmethod
    def from_newick(cls, newick: str) -> TreeBuilder: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def root(self) -> Node: ...
    def nodes(self) -> list[Node]: ...
    def is_leaf(self, node: NodeId) -> bool: ...
    def is_binary(self) -> bool: ...
    def children_of(self, node: NodeId) -> list[Node]: ...
    def parent_of(self, node: NodeId) -> Node | None: ...
    def name(self, node: NodeId) -> str | None: ...
    def node_metadata(self, node: NodeId) -> str | None: ...
    def edge_length(self, child: NodeId) -> float | None: ...
    def edge_metadata(self, child: NodeId) -> str | None: ...
    def preorder(self) -> list[Node]: ...
    def postorder(self) -> list[Node]: ...
    def add_node(
        self,
        parent: NodeId,
        name: str | None = None,
        length: float | None = None,
        node_metadata: str | None = None,
        edge_metadata: str | None = None,
    ) -> Node: ...
    def add_edge(
        self,
        parent: NodeId,
        child: NodeId,
        length: float | None = None,
        metadata: str | None = None,
    ) -> None: ...
    def remove_edge(
        self, parent: NodeId, child: NodeId
    ) -> tuple[float | None, str | None]: ...
    def replace_parent(self, child: NodeId, new_parent: NodeId) -> None: ...
    def set_root(self, node: NodeId) -> None: ...
    def set_name(self, node: NodeId, name: str | None) -> None: ...
    def set_node_metadata(self, node: NodeId, metadata: str | None) -> None: ...
    def set_edge_length(self, child: NodeId, length: float | None) -> None: ...
    def set_edge_metadata(self, child: NodeId, metadata: str | None) -> None: ...
    def add_hybrid_edge(self, parent: NodeId, child: NodeId) -> None: ...
    def remove_hybrid_edge(self, parent: NodeId, child: NodeId) -> None: ...
    def validate(self) -> None: ...
    def to_binary(self) -> BinaryTree: ...
    def to_newick(self) -> str: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...

class SvgOptions:
    def __init__(
        self,
        x_scale: float = 100.0,
        y_scale: float = 30.0,
        margin: float = 20.0,
        node_radius: float = 3.0,
        font_size: float = 12.0,
        show_names: bool = True,
    ) -> None: ...

class BinaryTree:
    @classmethod
    def random(cls, num_leaves: int, rng: RNG) -> BinaryTree: ...
    @classmethod
    def from_newick(cls, newick: str) -> BinaryTree: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_leaves(self) -> int: ...
    @property
    def num_internals(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def root(self) -> Internal: ...
    def nodes(self) -> list[Node]: ...
    def leaves(self) -> list[Leaf]: ...
    def internals(self) -> list[Internal]: ...
    def edges(self) -> list[Node]: ...
    def is_leaf(self, node: NodeId) -> bool: ...
    def is_internal(self, node: NodeId) -> bool: ...
    def children_of(self, node: NodeId) -> tuple[Node, Node]: ...
    def parent_of(self, node: NodeId) -> Internal | None: ...
    def name(self, node: NodeId) -> str | None: ...
    def node_metadata(self, node: NodeId) -> str | None: ...
    def edge_length(self, child: NodeId) -> float | None: ...
    def edge_metadata(self, child: NodeId) -> str | None: ...
    def leaf_by_name(self, name: str) -> Leaf | None: ...
    def nhx(self, node: NodeId, key: str) -> str | None: ...
    def preorder(self) -> list[Node]: ...
    def postorder(self) -> list[Node]: ...
    def to_newick(self) -> str: ...
    def layout(
        self, kind: str = "rectangular", separation: float = 1.0
    ) -> list[tuple[float, float]]: ...
    def to_svg(
        self,
        kind: str = "rectangular",
        separation: float = 1.0,
        options: SvgOptions | None = None,
        node_color: str = "#222222",
        edge_color: str = "#222222",
    ) -> str: ...
    def robinson_foulds(self, other: BinaryTree) -> int: ...
    def branch_score(self, other: BinaryTree) -> float: ...
    def triplet_distance(self, other: BinaryTree) -> int: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...

def branch_score_matrix(trees: list[BinaryTree]) -> array: ...
def robinson_foulds_matrix(trees: list[BinaryTree]) -> list[list[int]]: ...
def triplet_distance_matrix(trees: list[BinaryTree]) -> array: ...

class TaxonSet:
    def __init__(self, names: list[str]): ...
    @classmethod
    def ranged_ints(_cls, len: int) -> TaxonSet: ...
    def __iter__(self) -> Iterator[str]: ...
