from typing import SupportsFloat

from aspartik.distributions import (
    Continuous,
    Sample,
    Statistics,
)

class Beta(Continuous, Statistics, Sample[float]):
    def __init__(self, shape_a: SupportsFloat, shape_b: SupportsFloat): ...
    @property
    def shape_a(self) -> float: ...
    @property
    def shape_b(self) -> float: ...

class Exponential(Continuous, Statistics, Sample[float]):
    def __init__(self, rate: SupportsFloat): ...
    @property
    def rate(self) -> float: ...

class Gamma(Continuous, Statistics, Sample[float]):
    def __init__(self, shape: SupportsFloat, rate: SupportsFloat): ...
    @property
    def shape(self) -> float: ...
    @property
    def rate(self) -> float: ...

class InverseGamma(Continuous, Statistics, Sample[float]):
    def __init__(self, shape: SupportsFloat, rate: SupportsFloat): ...
    @property
    def shape(self) -> float: ...
    @property
    def rate(self) -> float: ...

class Laplace(Continuous, Statistics, Sample[float]):
    def __init__(self, location: SupportsFloat, scale: SupportsFloat): ...
    @property
    def location(self) -> float: ...
    @property
    def scale(self) -> float: ...

class LogNormal(Continuous, Statistics, Sample[float]):
    def __init__(self, location: SupportsFloat, scale: SupportsFloat): ...
    @property
    def location(self) -> float: ...
    @property
    def scale(self) -> float: ...

class Normal(Continuous, Statistics, Sample[float]):
    def __init__(self, mean: SupportsFloat, std_dev: SupportsFloat): ...
    @property
    def mean(self) -> float: ...
    @property
    def std(self) -> float: ...

class Uniform(Continuous, Statistics, Sample[float]):
    def __init__(self, min: SupportsFloat, max: SupportsFloat): ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
