from __future__ import annotations

from os import PathLike
from typing import BinaryIO, TextIO

from ..data.fasta import DNARecord
from ..data.msa import MSA

class FastaReader:
    def __init__(self, reader: TextIO | BinaryIO): ...
    @classmethod
    def from_file(cls, path: str) -> FastaReader: ...
    def __iter__(self) -> FastaReader: ...
    def __next__(self) -> DNARecord: ...

def read_msa_from_fasta(path: str | PathLike) -> MSA: ...
