from __future__ import annotations

from collections.abc import Sequence
from os import PathLike

class Logger:
    def __init__(self): ...
    def with_targets(self, targets: Sequence[str]) -> Logger: ...
    def to_file(self, path: str) -> PathLike: ...
    def init(self) -> None: ...
