[package]
name = "tracer"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
hashbrown = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
tracing-core = { workspace = true }

[lints]
workspace = true
