from .b3 import Tree, Parameter, Prior

class _b3_rust_impl:
    class Yule(Prior):
        def __init__(self, tree: Tree, birth_rate: Parameter): ...

class _data_rust_impl: ...
class _io_rust_impl: ...
class _rng_rust_impl: ...
class _stats_rust_impl: ...
