[workspace]
resolver = "2"
members = [
	"crates/aspartik",
	"crates/b3",
	"crates/bitmap",
	"crates/data",
	"crates/io",
	"crates/linalg",
	"crates/logger",
	"crates/math",
	"crates/rng",
	"crates/skvec",
	"crates/stats",
	"crates/util",
]

[workspace.package]
version = "0.1.0-alpha.4"
edition = "2024"
license = "AGPL-3.0-only"
authors = ["Andrej Kolčin <self@kaathewise.net>"]
repository = "https://github.com/kaathewisegit/aspartik"

[workspace.dependencies]
anyhow = "1.0"
arbitrary = "1.4"
arbtest = "0.3.2"
blake3 = "1.8"
bytemuck = "1.24"
bytes = "1.11"
cudarc = { git = "https://github.com/kaathewisegit/cudarc", branch = "array-repr", default-features = false }
divan = "0.1.21"
fork_union = "2.3"
indoc = "2.0"
libc = "0.2.180"
num-traits = "0.2.19"
parking_lot = "0.12.5"
peg = "0.8.5"
petgraph = { version = "0.8.3", default-features = false }
pyo3 = "0.27.2"
rand = { version = "0.10.0-rc.6", default-features = false }
rand_pcg = "0.10.0-rc.6"
rmp = "0.8.15"
rmp-serde = "1.3"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"

b3 = { version = "0.1.0-alpha.4", path = "crates/b3" }
bitmap = { version = "0.1.0-alpha.4", path = "crates/bitmap" }
data = { version = "0.1.0-alpha.4", path = "crates/data" }
io = { version = "0.1.0-alpha.4", path = "crates/io" }
linalg = { version = "0.1.0-alpha.4", path = "crates/linalg" }
logger = { version = "0.1.0-alpha.4", path = "crates/logger" }
math = { version = "0.1.0-alpha.4", path = "crates/math" }
rng = { version = "0.1.0-alpha.4", path = "crates/rng" }
skvec = { version = "0.1.0-alpha.4", path = "crates/skvec" }
stats = { version = "0.1.0-alpha.4", path = "crates/stats" }
util = { version = "0.1.0-alpha.4", path = "crates/util" }

[workspace.lints.clippy]
branches_sharing_code = "warn"
cast_lossless = "warn"
default_trait_access = "warn"
derive_partial_eq_without_eq = "warn"

# String API is much nicer to work with than the formatting one
to_string_trait_impl = "allow"

[profile.profile]
inherits = "release"
debug = true
