[workspace]
resolver = "2"
members = [
	"crates/b3",
	"crates/bitmap",
	"crates/data",
	"crates/io",
	"crates/linalg",
	"crates/rng",
	"crates/skvec",
	"crates/stats",
	"crates/util",
]

[workspace.package]
version = "0.1.0-alpha.2"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Andrej Kolčin <self@kaathewise.net>"]
repository = "https://github.com/kaathewisegit/aspartik"

[workspace.dependencies]
anyhow = "1.0"
approx = "0.5"
bytemuck = "1.23"
crossbeam-channel = "0.5.15"
cudarc = { version = "0.16.4", default-features = false }
divan = "0.1"
hashbrown = "0.15.3"
lapack-sys = "0.15"
nom = "8.0"
num-traits = "0.2"
parking_lot = "0.12"
petgraph = { version = "0.8", default-features = false }
proptest = "1.6"
pyo3 = "0.25"
rand = { version = "0.9", default-features = false }
rand_distr = "0.5"
rand_pcg = "0.9"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.19"

b3 = { version = "0.1.0-alpha.2", path = "crates/b3" }
bitmap = { version = "0.1.0-alpha.2", path = "crates/bitmap" }
data = { version = "0.1.0-alpha.2", path = "crates/data" }
io = { version = "0.1.0-alpha.2", path = "crates/io" }
linalg = { version = "0.1.0-alpha.2", path = "crates/linalg" }
rng = { version = "0.1.0-alpha.2", path = "crates/rng" }
skvec = { version = "0.1.0-alpha.2", path = "crates/skvec" }
stats = { version = "0.1.0-alpha.2", path = "crates/stats" }
util = { version = "0.1.0-alpha.2", path = "crates/util" }

[workspace.lints.clippy]
branches_sharing_code = "warn"
cast_lossless = "warn"
default_trait_access = "warn"
derive_partial_eq_without_eq = "warn"

[profile.bench]
debug = true

[package]
name = "aspartik"
description = "Computational biology toolkit"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
pyo3 = { workspace = true, features = ["anyhow"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }

b3 = { workspace = true }
data = { workspace = true }
io = { workspace = true }
rng = { workspace = true }
stats = { workspace = true }

[features]
cuda = ["b3/cuda"]
