[workspace]
resolver = "2"
members = [
	"crates/aspartik",
	"crates/b3",
	"crates/bitmap",
	"crates/buffer",
	"crates/data",
	"crates/distributions",
	"crates/io",
	"crates/linalg",
	"crates/rng",
	"crates/sk",
	"crates/util",
	"crates/verbatim",
]

[workspace.package]
version = "0.1.0-alpha.20"
edition = "2024"
license = "AGPL-3.0-only"
authors = ["Andrej Kolčin <self@kaathewise.net>"]
repository = "https://github.com/kaathewisegit/aspartik"

[workspace.dependencies]
anyhow = "1.0"
arbitrary = "1.4"
arbtest = "0.3.2"
blake3 = "1.8"
bytemuck = "1.25"
bytes = "1.12"
computare-core = { git = "https://github.com/kaathewisegit/computare", version = "0.1.0-alpha.0" }
computare-distributions = { git = "https://github.com/kaathewisegit/computare", version = "0.1.0-alpha.0" }
computare-special = { git = "https://github.com/kaathewisegit/computare", version = "0.1.0-alpha.0" }
cudarc = { version = "0.19.8", default-features = false }
fork_union = "2.3"
libc = "0.2.186"
num-traits = "0.2.19"
parking_lot = "0.12.5"
peg = "0.8.6"
picoarrow = "0.1.0"
pyo3 = "0.29.0"
rand = { version = "0.10.2", default-features = false }
rand_pcg = "0.10.2"
thiserror = "2.0"

b3 = { version = "0.1.0-alpha.20", path = "crates/b3" }
bitmap = { version = "0.1.0-alpha.20", path = "crates/bitmap" }
buffer = { version = "0.1.0-alpha.20", path = "crates/buffer" }
data = { version = "0.1.0-alpha.20", path = "crates/data" }
distributions = { version = "0.1.0-alpha.20", path = "crates/distributions" }
io = { version = "0.1.0-alpha.20", path = "crates/io" }
linalg = { version = "0.1.0-alpha.20", path = "crates/linalg" }
rng = { version = "0.1.0-alpha.20", path = "crates/rng" }
sk = { version = "0.1.0-alpha.20", path = "crates/sk" }
util = { version = "0.1.0-alpha.20", path = "crates/util" }
verbatim = { version = "0.1.0-alpha.20", path = "crates/verbatim" }

[workspace.lints.clippy]
branches_sharing_code = "warn"
cast_lossless = "warn"
default_trait_access = "warn"
derive_partial_eq_without_eq = "warn"
undocumented_unsafe_blocks = "warn"

# String API is much nicer to work with than the formatting one
to_string_trait_impl = "allow"

[profile.profile]
inherits = "release"
debug = true
