[project]
name = "aspartik"
dynamic = ["version", "author", "license"]
# Uses compression.zstd (PEP 784)
requires-python = ">=3.14"
classifiers = [
	"Programming Language :: Rust",
	"Programming Language :: Python :: Implementation :: CPython",
	"Typing :: Typed",
	"Topic :: Scientific/Engineering",
	"Topic :: Scientific/Engineering :: Bio-Informatics",
	"Intended Audience :: Developers",
	"Intended Audience :: Science/Research",
]
keywords = ["bioinformatics"]

[project.optional-dependencies]
dev = [
	"maturin[patchelf]~=1.10 ; sys_platform == 'linux'",
	"maturin~=1.10 ; sys_platform != 'linux'",
	"mpmath~=1.3",
	"numpy~=2.3",
	"pandas~=2.3",
	"pdoc~=16.0",
	"ty~=0.0.17",
	"pytest~=9.0",
	"ruff~=0.14.5"
]

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "aspartik._aspartik_rust_impl"
manifest-path = "crates/aspartik/Cargo.toml"
features = ["pyo3/extension-module"]

[tool.pytest]
testpaths = ["python/tests"]
python_files = ["*.py"]
strict_markers = true
markers = [
	"manual: slow tests which shouldn't be executed by default"
]

[tool.pyright]
reportUnsupportedDunderAll = false

[tool.ruff.lint]
select = ["E", "I", "W", "RUF"]
ignore = ["E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
section-order = [
	"future",
	"third-party",
	"standard-library",
	"first-party",
	"local-folder",
]
known-first-party = ["aspartik"]
