[project]
name = "aspartik"
dynamic = ["version", "author", "license"]
# Uses square bracket generics (PEP 695)
requires-python = ">=3.12"
classifiers = [
	"Programming Language :: Rust",
	"Programming Language :: Python :: Implementation :: CPython",
	"Typing :: Typed",
	"Topic :: Scientific/Engineering",
	"Topic :: Scientific/Engineering :: Bio-Informatics",
	"Intended Audience :: Developers",
	"Intended Audience :: Science/Research",
]
keywords = ["bioinformatics"]

[project.optional-dependencies]
dev = [
	"maturin[patchelf]~=1.8 ; sys_platform == 'linux'",
	"maturin~=1.8 ; sys_platform != 'linux'",
	"pyright~=1.1",
	"pdoc~=15.0",
	"pytest~=8.4",
	"mpmath~=1.3",
	"numpy~=2.3",
	"ruff~=0.12.3"
]

[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "aspartik._aspartik_rust_impl"
manifest-path = "crates/aspartik/Cargo.toml"
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
testpaths = ["python/tests"]
python_files = "*.py"

[tool.pyright]
reportUnsupportedDunderAll = false

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
section-order = [
	"future",
	"third-party",
	"standard-library",
	"first-party",
	"local-folder",
]
known-first-party = ["aspartik"]
