[package]
name = "b3"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bitmap = { workspace = true }
buffer = { workspace = true }
data = { workspace = true }
io = { workspace = true }
linalg = { workspace = true }
math = { workspace = true }
rng = { workspace = true }
sk = { workspace = true }
stats = { workspace = true }
util = { workspace = true }
verbatim = { workspace = true }

anyhow = { workspace = true }
blake3 = { workspace = true }
bytemuck = { workspace = true, features = ["derive", "extern_crate_alloc"] }
cudarc = { workspace = true, features = ["driver", "nvrtc", "dynamic-loading", "cuda-13000", "std"] }
fork_union = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
picoarrow = { workspace = true }
pyo3 = { workspace = true, features = ["anyhow"] }
rand = { workspace = true, features = ["alloc"] }
rand_pcg = { workspace = true }

[lints]
workspace = true
