[package]
name = "base"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nalgebra = { workspace = true }
petgraph = { workspace = true }
thiserror = { workspace = true }
