[package]
name = "base"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
linalg = { path = "../linalg" }

petgraph = { workspace = true }
thiserror = { workspace = true }
