[package]
name = "data"
description = "Bioinformatics data structures and Sans IO parsing"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
util = { workspace = true }

anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true, features = ["derive"] }
bytes = { workspace = true }
parking_lot = { workspace = true, optional = true }
peg = { workspace = true }
pyo3 = { workspace = true, features = ["anyhow"], optional = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
arbitrary = { workspace = true }
arbtest = { workspace = true }

[features]
default = ["python", "arbitrary"]
python = ["dep:pyo3", "dep:parking_lot"]
arbitrary = ["dep:arbitrary"]

[lints]
workspace = true
