[package]
name = "core"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
linalg = { path = "../linalg" }

anyhow = { workspace = true }
petgraph = { workspace = true }
thiserror = { workspace = true }
