[package]
name = "shchurvec"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dev-dependencies]
divan = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }

[[bench]]
name = "double"
harness = false
