from __future__ import annotations

from typing import BinaryIO, TextIO

from ..data import DNASeq

class DNARecord:
    def __init__(self, name: str, sequence: DNASeq): ...
    @property
    def sequence(self) -> DNASeq: ...
    @property
    def description(self) -> str: ...
    @property
    def id(self) -> str: ...

class DNAReader:
    def __init__(self, reader: TextIO | BinaryIO): ...
    @classmethod
    def from_file(cls, path: str) -> DNAReader: ...
    def __iter__(self) -> DNAReader: ...
    def __next__(self) -> DNARecord: ...
