[package]
name = "math"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
util = { workspace = true }

indoc = { workspace = true }
pyo3 = { workspace = true, features = ["multiple-pymethods"], optional = true }
thiserror = { workspace = true }

[dev-dependencies]
arbitrary = { workspace = true }
arbtest = { workspace = true }

[features]
default = ["python"]
python = ["dep:pyo3"]

[lints]
workspace = true
